let mapleader=' '              "The default leader is `\` , but a commaa is much batter.
let maplocalleader=' '

set expandtab
set shiftwidth=4
set tabstop=4
set softtabstop=4
set smartindent
set autoindent
set wrap
set number
set relativenumber
set wildmode=longest:full,full
set completeopt=menuone,longest,preview
set title
set mouse=a
set termguicolors
set spell
set ignorecase
set smartcase
set list
set listchars=tab:▸\ ,trail:·
set splitbelow
set splitright
set scrolloff=8
set sidescrolloff=8
set clipboard=unnamedplus
set confirm
set signcolumn=yes
set undofile
set backup
set backupdir:remove('.')

set iskeyword-=_

nnoremap [[ [mzz
nnoremap ]] ]mzz
