is_intellij_terminal() {
    [[ -n "$INTELLIJ_ENVIRONMENT_READER" || -n "$FIG_JETBRAINS_SHELL_INTEGRATION" || -n "$TERMINAL_EMULATOR" ]]
}

#--------------------------------------------------------------------------
# Oh My Zsh
#--------------------------------------------------------------------------

export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="agnoster"
ZSH_TMUX_AUTOSTART=false
HYPHEN_INSENSITIVE="true"
COMPLETION_WAITING_DOTS="true"
HIST_STAMPS="yyyy-mm-dd"
export NVM_DIR="$HOME/.nvm"
export HOMEBREW_AUTO_UPDATE_SECS="86400"

plugins=(
    git
    zsh-autosuggestions
    zsh-syntax-highlighting
    docker
    docker-compose
    z
    npm
    fzf
    composer
    httpie
)

# kitty 또는 ghostty 터미널에서 tmux 자동 시작
if [[ -n "$KITTY_WINDOW_ID" || -n "$GHOSTTY_TERMINAL" ]]; then
    export ZSH_TMUX_AUTOSTART=true
    plugins+=(tmux)
    cd $HOME/code
fi

# Idea 예외처리
if is_intellij_terminal; then
    path=(
        $NVM_BIN  # nvm.sh가 로드되면 NVM_BIN이 설정됩니다
        $HOME/.yarn/bin
        $HOME/.config/yarn/global/node_modules/.bin
        "$HOME/Library/Application Support/Herd/bin/"
        $path
    )
fi

source $ZSH/oh-my-zsh.sh

#--------------------------------------------------------------------------
# Configuration
#--------------------------------------------------------------------------
typeset -U PATH path cdpath fpath
export GOPATH=$HOME/go
if [ "$(/usr/bin/uname)" = "Darwin" ]; then
  export GOROOT="$(/opt/homebrew/bin/brew --prefix golang)/libexec"
else
  export GOROOT="/usr/local/go"
fi

export ANDROID_HOME=$HOME/Library/Android/sdk
export RBENV_PATH=$HOME/.rbenv/shims

path=(
    /usr/local/bin
    /usr/bin
    /bin
    /usr/sbin
    /sbin
    $HOME/.local/bin
    $HOME/.config/composer/vendor/bin
    $GOPATH/bin
    $GOROOT/bin
    $HOME/.cargo/bin
    ./vendor/bin
    ${ANDROID_HOME}/emulator
    ${ANDROID_HOME}/platform-tools
    $RBENV_PATH
    /opt/homebrew/opt/mysql/bin
    /opt/homebrew/opt/mysql-client/bin
    /opt/homebrew/opt/libpq/bin
    $path
)

setopt auto_cd
cdpath=(
    $HOME/code
)

export EDITOR=vim
export GIT_EDITOR=vim
export FZF_DEFAULT_COMMAND='ag -u -g ""'

unsetopt sharehistory

[ -s "$(brew --prefix nvm)/nvm.sh" ] && \. "$(brew --prefix nvm)/nvm.sh"
[ -s "$(brew --prefix nvm)/etc/bash_completion.d/nvm" ] && \. "$(brew --prefix nvm)/etc/bash_completion.d/nvm"

#--------------------------------------------------------------------------
# Aliases
#--------------------------------------------------------------------------
alias k='kubectl'
alias he='helm'
alias sail='[ -f sail ] && bash sail || bash vendor/bin/sail'
alias pn='pnpm'

[ -x "$(command -v bat)" ] && alias cat="bat --paging=never" || alias cat="batcat --paging=never"
[ -x "$(command -v lvim)" ] && alias vim="lvim"

#--------------------------------------------------------------------------
# Miscellaneous
#--------------------------------------------------------------------------
[ -f ~/.private-exports ] && source $HOME/.private-exports

bindkey "^[[1;3C" forward-word
bindkey "^[[1;3D" backward-word

export LANG=en_US.UTF-8 # k9s 깨짐 문제 해결

# bun
export TMPDIR=/tmp
export BUN_RUNTIME_TRANSPILER_CACHE_PATH=/tmp/bun-cache
export BUN_INSTALL_CACHE_DIR=/tmp/bun-cache
[ -s "$HOME/.bun/_bun" ] && source "$HOME/.bun/_bun"

# pnpm
export PNPM_HOME="$HOME/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end

# rbenv
eval "$(rbenv init - --no-rehash zsh)"

alias claude-mem='bun "~/.claude/plugins/marketplaces/thedotmack/plugin/scripts/worker-service.cjs"'
